### ISSUE TITLE
CODE RUB: TryCatch Fix Cosmos -> Sql

### ISSUE THREAD

**Issue by glhays** [The-Standard-Organization/STX.EFxceptions.SqlServer#16]
@cjdutoit noticed in the TryCatch method the first catch is Cosmos, I think it should be Sql. Just a variable naming fix.

**Comment by ZafarUrakov** [comment]
> @cjdutoit noticed in the TryCatch method the first catch is Cosmos, I think it should be Sql. Just a variable naming fix.

Yeah, will be fixed
